### ISSUE TITLE
Feature request: adding maxit argument to multinom call in gformula_survival function 

### ISSUE THREAD

**Issue by jerzEG** [CausalInference/gfoRmula#1]
Hi,

I'm having convergence issues when fitting multinomial models for categorical time-varying covariates. I was wondering if you could add a maxit argument to the gformula_survival function so that users can increase the maximum number of iterations above 100. Thanks so much for the help - the package has been really useful in my work thus far.   

Best,

Jerzy Eisenberg-Guyot

**Comment by stmcg** [comment]
Hi Jerzy,

Thanks for the suggestion. You can now specify the parameters of the fitting process (such as the maximum number of iterations) for the time-varying covariates using covparams$control. 

Specifically, covparams$control should be a list of the same length as covnames, where the j-th entry of covparams$control is a list that specifies the parameters of the fitting process for the j-th entry in covnames. For covtypes "binary", "normal", "bounded normal", and "absorbing", the entry in covparams$control is passed to the control argument of glm(); For covtype "categorical", the entry in covparams$control is passed into the nnet() fitting function; For covtype "truncated normal", the entry in covparams$control is passed into the truncreg.fit() function; For covtype "zero-inflated normal", the entry in covparams$control should be a list of length two, where the first element is passed to the control argument of glm() for the binomial GLM and the second element is passed to the control argument of glm() for the Gaussian GLM.

For instance, in the default example for a continuous end of follow-up outcome, one can specify a maximum of 200 iterations for the categorical covariate L1 by

```
covparams <- list(covmodels = c(L1 ~ lag1_A + lag1_L1 + L3 + t0 +
                                  rcspline.eval(lag1_L2, knots = c(-1, 0, 1)),
                                L2 ~ lag1_A + L1 + lag1_L1 + lag1_L2 + L3 + t0,
                                A ~ lag1_A + L1 + L2 + lag1_L1 + lag1_L2 + L3 + t0),
                  control = c(list(maxit = 200), NA, NA))
```

Best,
Sean
