### ISSUE TITLE
End of follow up - survival analyses

### ISSUE THREAD

**Issue by MarieBu88** [CausalInference/gfoRmula#10]
Dear authors,

Thank you very much for the package gfoRmula and the related documentation.

I am trying to implement the g-formula in R to determine the risk of cardiovascular events related to occupational exposures, using a survival type of outcome. These interventions would be exposures in the 10 first years of follow-up, followed by no exposure, and I would be interested in seeing their effect on the risk of events when subjects attain a specific age (for example 60 years old), but the age at the beginning of follow-up is not the same for all subjects. Is there a way I could set the intervention parameters to implement this kind of intervention ?

Many thanks in advance for your help,

Marie

**Comment by stmcg** [comment]
Hi Marie,

Thanks for posting and apologies for the delay in getting back to you. The package can't run this type of analysis, as it's designed to estimate risks at fixed times after baseline for everyone. 

Best,
Sean

**Comment by MarieBu88** [comment]
Thank you very much for your answer Sean.

Best,
Marie
