### ISSUE TITLE
Issues with specifying continuous time-varying covariates with the stats::weighted.means() function?

### ISSUE THREAD

**Issue by jerbear1992** [CausalInference/gfoRmula#14]
Hello Sean,

First, this is a fantastic package and very important for the works of many people intending to apply this to their works. I'm currently fumbling around with an issue where it appears that whenever I specify a continuous time-varying covariate, I am thrown this error "Error in weighted.mean.default(x = obs_data[cur_time_ind][[covname]],  :  'x' and 'w' must have the same length".

The traceback reveals that it comes from the function obs_calculate, when the weighted mean function "stats::weighted.mean(x = obs_data[cur_time_ind][[covname]], w = w[prev_time_ind], na.rm = TRUE)" is applied.

I dug a bit more on this, and found what I think was the source of the function from the 'comparisons.R' file, which intends to calculate observed covariate means and risk. The weighted.means method in this file is trying to calculate the covariate means at each time point. To my understanding, this entails getting the observed rows of the covariate in question from the current time point ('x=obs_data[cur_time_ind][[covname]]') and using the rows of the covariate from the previous time point as weights ('w = w[prev_time_ind]'). These two are fitted into the stats::weighted.means(). 

If the error are that the x and w vectors are not of the same length, it first made me do a general assessment of my dataset. I had thought that perhaps either I had missing values which was throwing this function off or perhaps I had uneven, incomplete cases (e.g. say that I had 3 time points in my data, maybe I have some individuals who have only have data in time point 2 or 3 but not all 3 time points). But after checking this, neither of these concerns I had appear to be the issue.

It also appears that this error is only thrown when a continuous time-varying covariate is added, whereas binary and categorical covariates only allow the model to run at least, albeit with some warnings. My dataset has roughly 10,458 observations evenly split between three time points and I am using the continuous end of follow-up version as well. My treatment var is categorical, and baseline covs are a mix of categorical, binary, and continuous. For the time-varying covariates I am considering using lagged or cumulative average specifications.

Anyways, let me know if you are able to provide me some suggestions, and of course, if you have questions for me on the context of the dataset I'm using I'm more than happy to provide them.

**Comment by jerbear1992** [comment]
FYI just solved this by making sure that the identifier variable (id) started from 1, 2, ..... Originally, the dataset I had IDs that were not sequenced this way and thus they were not iteratively adding up.

**Comment by stmcg** [comment]
Hi Jerry, 

Thanks for posting and for the update. I'm glad to hear that the issue is resolved after fixing the IDs. Feel free to write back if any other issues arise
