### ISSUE TITLE
How to calcualte the Restricted Mean Survival Times

### ISSUE THREAD

**Issue by LR1933** [CausalInference/gfoRmula#15]
Many thanks for your great package.

I found some studies using SAS macro calcualte the Restricted Mean Survival Times. For, example, [Refining the Association Between Body Mass Index and Atrial Fibrillation: G‐Formula and Restricted Mean Survival Times](https://www.ahajournals.org/doi/10.1161/JAHA.119.013011). 

How to calculate it in gfoRmula package.

**Comment by stmcg** [comment]
Thanks for posting. The R package doesn't include the restricted mean survival times in the output. But, I believe you can calculate the restricted mean survival times based on the package output. Specifically, the output of the `gformula` function includes the component `dt_out_plot` which contains the parametric g-formula estimates of the survival probabilities at each time point. My understanding is that these survival probabilities can be summed to compute the restricted mean survival times

**Comment by stmcg** [comment]
I'm closing this issue since it has been a few months, but please let me know if you have any follow-up questions
