### ISSUE TITLE
Error message in v1.0.2 but not in v1.0.0

### ISSUE THREAD

**Issue by suthlam** [CausalInference/gfoRmula#16]
Thank you for creating this package! I used the gformula_survival function in v1.0.0 to estimate the cumulative mortality rates under some hypothetical interventions last year but the application of the same function in v1.0.2 to the same dataset led to an error message: "
Error in weighted.mean.default(x = obs_data[cur_time_ind][[covname]],  : 
  'x' and 'w' must have the same length
"
Do you have any insights on what might be causing the error? I have a relatively simple scenario of time-varying exposure and confounders with no loss-to-followup or competing events. You could see the codes and mock dataset I used [here](https://github.com/suthlam/cchs_g_computation). Thank you for your help!

Chen

**Comment by stmcg** [comment]
Hi Chen,

Thanks for the message. I believe this issue will be resolved if either (a) you use the current development version of the package on GitHub, or (b) you re-name the ID variable in your data set to `id`. A few other users reported this issue, and our most recent commit on GitHub aims to resolve this. 

Best,
Sean

**Comment by suthlam** [comment]
Thank you for the prompt reply! I confirm that the error message gets resolved by changing the ID variable to id. Do you have a timeline for the release of a new version that incorporates this recent commit?

**Comment by stmcg** [comment]
That's great to hear. I'll aim to release the new version on CRAN in the next week or so
