### ISSUE TITLE
Command returns error in intervention

### ISSUE THREAD

**Issue by flxflks** [CausalInference/gfoRmula#18]
I am using the ``gformula`` package in R to estimate the effect of a natural treatment history on my dependent variable. My data is unbalanced panel data, with missing values on the DV and some covariates. 
When I try to run the following code: 
```
gformula(obs_data = dt, outcome_type = 'continuous_eof', id= 'country_iso3', time_name = 'recode_year', seed = 1234, outcome_name = 'newbusiness', covnames = c('totalnumber', 'nkillwound', 'GDPppp'), covtypes = c('zero-inflated normal', 'zero-inflated normal' ,"normal"), intvars = c('totalnumber', 'nkillwound'), interventions = c('natural', 'natural'), histvars = list(c('totalnumber', 'nkillwound', 'GDPppp'), c('totalnumber', 'nkillwound', 'GDPppp')), histories = c(lagged, cumavg), covparams = list(covmodels = c(totalnumber ~ lag1_totalnumber + cumavg_totalnumber, nkillwound ~ lag1_nkillwound + cumavg_totalnumber, GDPppp ~ lag1_GDPppp + lag1_totalnumber + lag1_nkillwound + cumavg_totalnumber + cumavg_nkillwound)), ymodel = newbusiness ~ nkillwound + GDPppp + lag1_totalnumber + lag1_nkillwound)
```
I get the following error message:
```
Error in intervention[[i]][[1]](newdf, pool, intvar[i], intvals = NULL,  : 
  attempt to apply non-function
In addition: There were 19 warnings (use warnings() to see them)
```
17 out of the 19 warnings are: 
```
In stats::rnorm(x, mean, est_sd) : NAs produced
```
I have read the accompanying article to the package as well as the `help gformula` to try and see if there is any documentation mentioning if and how the package gformula handles missing data. Thus, I was wondering, if gformula does or does not work with missing data?
[
Crossposted on Stackoverflow (SO)](https://stackoverflow.com/questions/76754576/gformula-package-retruns-error-in-intervention.)

**Comment by stmcg** [comment]
Hi, thanks for posting. 

The first error message relates to the specified intervention. The argument `interventions` should contain lists which have the intervention function (e.g., `static`) and any additional input parameters rather than a string such as `'natural'`. Also, since the package automatically includes the natural course intervention, there is generally no need to specify the natural course intervention.

As far as missing data -- The package handles some types of censoring / missing data, such as visit processes attached to covariates, although it has some requirements on the structure of the input data set and application of the `gformula` function. It’s hard to give more concrete advice on this without additional information on the type of missing data you have

EDIT: One additional comment -- 

There are also some issues with the covariate models due to using cumavg in the model for the same variable. It might be better to use the lagged cumavg predictor instead

**Comment by flxflks** [comment]
Hi! Thank you so much for your reply. I went back today and changed the code so that invterventions are set to 'dynamic' and I have gotten rid of the cumavg variables for the moment. I still get the same error, so I am assuming it has to do with my missing data. As for the missigness, what information would you need? I have a country-level panel data set. My DV is probably missing systematically within countries.

The updated code is here:
gformula(obs_data = dt, outcome_type = 'continuous_eof', id= 'country_iso3', time_name = 'recode_year', seed = 1234, outcome_name = 'newbusiness', covnames = c('totalnumber', 'nkillwound', 'GDPppp'), covtypes = c('zero-inflated normal', 'zero-inflated normal' ,"normal"), intvars = c('nkillwound'), interventions = 'dynamic', histvars = list(c('totalnumber', 'nkillwound', 'GDPppp')), histories = c(lagged), covparams = list(covmodels = c(totalnumber ~ lag1_totalnumber, nkillwound ~ lag1_nkillwound + totalnumber, GDPppp ~ lag1_GDPppp + lag1_totalnumber + lag1_nkillwound)), ymodel = newbusiness ~ nkillwound + GDPppp + lag1_totalnumber + lag1_nkillwound)

**Comment by rwlogan** [comment]
As a suggestion, try running the program with no interventions to see if the natural course will run. I would need to check how interventions need to be set in the call. I am not sure if "dynamic" is enough information.

For the missing values, I don't know if there is an assumption that there are no missing values at baseline. Since these values are used for initiating a simulated follow-up, if any covariates are missing then the complete simulated follow-up will be missing. As a test, remove all subjects who have missing values at baseline.

**Comment by flxflks** [comment]
Hello again! My apologies for the long absence, I had to switch to another project and I have no returned to this project. I have tried to run the code without missing values. When I run the code without interventions and without missing data. I have tried to three ways to get rid of the missing data. I have just replaced the missing data with 0, with more or less realistic numbers based on my "expert knowledge" and I have just selected a few observations with full data for a slightly smaller time period. For all these, I get the following error when I try running the program with no interventions:
`Error in int_result/ref_mean : non-numeric argument to binary operator`.

**Comment by rwlogan** [comment]
Can you post the updated call statement you are using that produces this error?

**Comment by flxflks** [comment]
Yes, of course, my apologies. I imported the data from Stata, so I stripped every attribute from the data. All variables are numeric. 
The code: 
gformula(
  obs_data = subset2,
  id = 'country_iso3',
  time_name = 'recode_year',
  outcome_type = 'continuous_eof',
  outcome_name = 'newbusiness',
  covnames = c('totalnumber', 'nkillwound', 'GDPppp'),
  covtypes = c('normal', 'normal' , "normal"),
  covparams = list(
    covmodels = c(
      totalnumber ~ lag1_totalnumber,
      nkillwound ~ lag1_nkillwound,
      GDPppp ~ lag1_GDPppp + lag1_totalnumber + lag1_nkillwound
    )
  ),
  histvars = list(c('totalnumber', 'nkillwound', 'GDPppp')),
  histories = c(lagged),
  ymodel = newbusiness ~ nkillwound + GDPppp + lag1_totalnumber + lag1_nkillwound,
  seed = 1234
  )

**Comment by stmcg** [comment]
Thanks for posting the code. This helped us uncover a bug in the package when no interventions are supplied and end of follow-up type outcomes are used. 

I just made an update to the GitHub version of the package to fix the bug. Can you re-install the GitHub version of the package and re-run your analysis?

**Comment by flxflks** [comment]
Thank you for making the package available and using Github, so that I could come here and report my problem! :) I am glad I could do my little part to help. 

I have re-installed the GitHub version of the package and re-run my analysis without any interventions. The code now returns:
```
REDICTED RISK UNDER MULTIPLE INTERVENTIONS

Intervention 	 Description
0 		 Natural course

Sample size = 95, Monte Carlo sample size = 95
Number of bootstrap samples = 0
Reference intervention = natural course (0)
 

  k Interv. NP mean g-form mean Mean ratio Mean difference
 13       0      NA    5.639046          1               0
 % Intervened On Aver % Intervened On
               0                    0
```

If I now try to specify my interventions using: 
```
gformula(
  obs_data = subset2,
  outcome_type = 'continuous_eof',
  id = 'country_iso3',
  time_name = 'recode_year',
  seed = 1234,
  outcome_name = 'newbusiness',
  covnames = c('totalnumber', 'GDPppp'),
  covtypes = c('zero-inflated normal', 'zero-inflated normal' , "normal"),
  intvars = c('nkillwound'),
  interventions = 'dynamic',
  histvars = list(c('totalnumber', 'GDPppp')),
  histories = c(lagged),
  intvars = 'nkillwound', 
  interventions = 'dynamic',
  covparams = list(
    covmodels = c(
      totalnumber ~ lag1_totalnumber,
      nkillwound ~ lag1_nkillwound + totalnumber,
      GDPppp ~ lag1_GDPppp + lag1_totalnumber + lag1_nkillwound
    )
  ),
  ymodel = newbusiness ~ nkillwound + GDPppp + lag1_totalnumber + lag1_nkillwound
)
```
I get the following error code: 
```
Error in gformula(obs_data = subset2, outcome_type = "continuous_eof",  : 
  formal argument "intvars" matched by multiple actual arguments
```
For clarification, I have country-level data and countries are exposed to different number of terror attacks causing different number of killed and wounded each year.

**Comment by stmcg** [comment]
Great to hear that your code now works without any interventions. 

For the new error message: It looks like it is due to specifying `intvars` twice in your call to the `gformula` function. Heads up on that this is also done for `interventions`
