### ISSUE TITLE
Specifying a custom intervention

### ISSUE THREAD

**Issue by yohei-h** [CausalInference/gfoRmula#19]
Thank you for this great package.

I'm reading the paper by McGarth et al. (2020). How to specify a custom intervention is shown in C.9.1 (Example 1: a dynamic intervention based on the current value of a time-varying covariate), which says as follows:

------------------------------------------------------------------------------------
The following is an example of a function that deﬁnes an intervention under which treatment is given only for individuals where L2 is above a certain threshold (provided in intvals):
```
example_intervention <- function(newdf, pool, intvar, intvals, time_name, t){ 
    newdf[(intvar) := 0]
    newdf[L2 < intvals[[1]], (intvar) := 1]
}
```

Supposing the user wants to set the threshold to 0.75, the function call would then be:
```
gformula(...,
                 intvars = list('A'), 
                 interventions = list(list(c(example_intervention, 0.75))))
```
------------------------------------------------------------------------------------

**Question 1**: In the example above, is `newdf[L2 > intvals[[1]], (intvar) := 1] `rather than `newdf[L2 < intvals[[1]], (intvar) := 1]` correct (reverse the inequality sign)?

**Question 2**: If we want to compare the above treatment strategy vs. "always treat", then should we write as follows?
```
outcome_type <- 'survival'
id <- 'id'
time_points <- 7                                     
time_name <- 't0'                                    
outcome_name <- 'Y'                                  
basecovs <- c('L3')                                  
covnames <- c('L1', 'L2', 'A')                       
covtypes <- c('binary', 'bounded normal', 'binary')  
histvars <- list(c('A', 'L1', 'L2'), c('L1', 'L2'))  
histories <- c(lagged, lagavg)                       
                                                                                        

covparams <- list(covmodels = c(L1 ~ lag1_A + lag_cumavg1_L1 + lag_cumavg1_L2 + L3 + t0,   
                                L2 ~ lag1_A + L1 + lag_cumavg1_L1 + lag_cumavg1_L2 + L3 + t0,
                                A ~ lag1_A + L1 + L2 + lag_cumavg1_L1 + lag_cumavg1_L2 + L3 + t0)) 

intvars <- list('A', 'A', 'A')    
                        
example_intervention <- function(newdf, pool, intvar, intvals, time_name, t){ 
    newdf[(intvar) := 0]
    newdf[L2 < intvals[[1]], (intvar) := 1]
}

interventions <- list(                               
    list(c(static, rep(0, time_points))),            
    list(c(static, rep(1, time_points))),            
    list(c(example_intervention, 0.75))   ########
)

ymodel <- Y ~ A + L1 + L2 + L3 + lag1_A + lag1_L1 + lag1_L2 + t0

int_descript <- c('Never treat', 'Always treat', 'Custom')
nsimul <- 10000

gform_basic <- gformula(
    obs_data = basicdata_nocomp,
    outcome_type = outcome_type,
    id = id,
    time_points = time_points,
    time_name = time_name,
    covnames = covnames,
    outcome_name = outcome_name,
    covtypes = covtypes,
    covparams = covparams,
    ymodel = ymodel,
    intvars = intvars,
    interventions = interventions,
    int_descript = int_descript,
    histories = histories,
    histvars = histvars,
    basecovs = basecovs,
    nsimul = nsimul,
    ref_int = 2,          ###########
    seed = 1234
)
```
I got the folloing error message after running this script...:

> Error in value[[3L]](cond) : 
>   Operator := detected in i, the first argument inside DT[...], but is only valid in the second argument, j. Most often, this happens when forgetting the first comma (e.g. DT[newvar := 5] instead of DT[ , new_var := 5]). Please double-check the syntax. Run traceback(), and debugger() to get a line number.
> Called from: value[[3L]](cond)

Many thanks!

**Comment by stmcg** [comment]
Thank you for posting. My responses are below:

**Question 1**: Yes, you are right. Good catch!

**Question 2**: The intervention function should be revised to the following:

```
example_intervention <- function(newdf, pool, intvar, intvals, time_name, t){ 
  newdf[, (intvar) := 0]
  newdf[L2 < intvals[[1]], (intvar) := 1]
}
```

The difference is changing ```newdf[(intvar) := 0]``` to ```newdf[, (intvar) := 0]```. I believe this is ultimately due to updated syntax requirements from the ```data.table``` package

**Comment by yohei-h** [comment]
Thank you for your detailed response. I understand now.
