### ISSUE TITLE
Error messages possibly from dependencies?

### ISSUE THREAD

**Issue by sally741** [CausalInference/gfoRmula#20]
Hi there, thanks for this package. I have used the SAS implementation of g-formula quite a bit but am currently trying to mentor someone using the R package. I know a little R, but not a lot. 
Our data involves a continuous outcome at end of follow-up, and at the moment we're just trying to intervene on a single binary (absorbing) exposure. There are a couple of baseline covariates and several time-varying covariates, but no censoring.
We have not been able to get the function to run. The first several errors were specific enough for us to debug, but now we have the following:
Error in crossprod(bb * X, X): non-conformable arguments
and
Warning: In rep(point, length.out = length(Y)): 'x' is NULL so the result will be NULL

The error in crossprod apparently means that we are trying to multiply two matrices/vectors that do not match up in dimensions, but I have no idea where this problem is occurring or how to solve it. Also, bb, X, and x are not variable names in our data, and I did not find them when I searched in the raw code for the gfoRmula package.

Do you have any idea what could be causing these errors? 
Thank you!
Best,
Sally

**Comment by stmcg** [comment]
Hi Sally,

Thank you for posting. It's difficult to tell what might be causing this error message without the code. Are you able to post the code?

As a sanity check (regarding package dependencies), are you able to run the examples in the package documentation (ie, in the help file for the `gformula` function)?

Best,
Sean

**Comment by sally741** [comment]
Thank you for responding so quickly! Yes, we are able to run the example from the package documentation. Thank you for suggesting that!

We cannot share the data so I've "anonymized" our variable names (and I had to hand-transcribe the code from the server where we run the analyses, so hopefully I didn't make any mistakes), but here is the code:

library(gfoRmula)
library(haven)
library(Hmisc)

data<-read_dta(‘[path]’)

id <- ‘dbn2’
time_name <- ‘time’
time_points <- 4
outcome_name <- ‘outcome’
outcome_type <- ‘continuous_eof’
histories <- c(lagged)
histvars <- list(c(‘plag’, ‘fyn’, ‘anayn’, ‘aapyn’, ‘gtyn’, ‘mtias’, ‘totenr’, ‘pfrpm’, ‘paa’, ‘pw’, ‘pas’, ‘po’)

basecovs <-c(‘ch’, ‘aco’)
covnames<-c(‘plag’, ‘totenr’, ‘pfrpm’, ‘paa’, ‘pw’, ‘pas’, ‘po’, ‘fyn’, ‘anayn’, ‘aapyn’, ‘gtyn’,  ‘mtias’)
covtypes<-c(‘bounded normal’, ‘normal’, ‘truncated normal’, ‘truncated normal’, 
                     ‘zero-inflated normal’, ‘zero-inflated normal’, ‘zero-inflated normal’, ‘absorbing’, ‘absorbing’, 
                     ‘absorbing’, ‘absorbing’, ‘binary’)
covparams <- list(covmodels=c(plag~lag1_fyn + time + ch + aco + lag1_anayn + lag1_aapyn + lag1_gtyn + 
                                                             lag1_mtias + lag1_totenr + lag1_pfrpm + lag1_paa + 
                                                             lag1_pw + lag1_pas + lag1_po,
					totenr~ lag1_totenr + time,
					pfrpm ~ time + totenr + lag1_pfrpm + lag1_paa + lag1_pw + lag1_pas + 
                                                       lag1_po,
					paa ~ time + totenr + pfrpm + lag1_paa + lag1_pw + lag1_pas + lag1_po,
					pw ~ time + totenr + pfrpm + paa + lag1_pw + lag1_pas + lag1_po,
					pas ~ time + totenr + pfrpm + paa + pw + lag1_pas + lag1_po,
					po ~ time + totenr + pfrpm + paa + pw + pas + lag1_po,
					fyn ~ time + ch + aco + lag1_anayn + lag1_aapyn + lag1_gtyn + 
                                                  lag1_mtias + totenr + pfrpm + paa + pw + pas + po,
					anayn ~ time + ch + aco + fyn + lag1_aapyn + lag1_gtyn + lag1_mtias + 
                                                      totenr + pfrpm + paa + pw + pas + po,
					aapyn ~ time + ch + aco + fyn + anayn + lag1_gtyn + lag1_mtias + 
                                                       totenr + pfrpm + paa + pw + pas + po,
					gtyn ~ time + ch + aco + fyn + anayn + aapyn + lag1_mtias + 
                                                     totenr + pfrpm + paa + pw + pas + po,
					mtias ~ time + ch + aco + fyn + anayn + aapyn + gtyn + lag1_mtias + 
                                                     totenr + pfrpm + paa + pw + pas + po
                                         ))
ymodel <- outcome ~ plag + ch + aco + fyn + anayn + aapyn + gtyn + mtias + totenr + pfrpm + paa + 
                                     pw + pas + po
intvars<-list(‘fyn’)
interventions<-list(list(c(static,rep(0,4))))
int_descript<-c(‘Never treated’)
seed<-888

gform_sl_1<- gformula(obs_data=data,id=id,time_name=time_name,time_points=time_points, 
                                      outcome_name=outcome_name, outcome_type=outcome_type, histories=histories,
                                      histvars=histvars, basecovs=basecovs, intvars=intvars,
                                      interventions=interventions, int_descript=int_descript, covnames=covnames,
                                      covtypes=covtypes, covparams=covparams, ymodel=ymodel, seed=seed, 
                                       )

Please let me know if you see any obvious issues! Thanks again!

**Comment by sally741** [comment]
Not sure what happened there with some stuff crossed out. Some weird formatting thing with the ~ symbol, I think. The covparams assignment should have been this:

covparams <- list(covmodels=c(plag ~ lag1_fyn + time + ch + aco + lag1_anayn + lag1_gtyn + 
                                                               lag1_mtias + lag1_totenr + lag1_pfrpm + lag1_paa + 
                                                               lag1_pw + lag1_pas + lag1_po,
					totenr ~ lag1_totenr + time,
					pfrpm ~ time + totenr + lag1_pfrpm + lag1_paa + lag1_pw + lag1_pas + 
                                                       lag1_po,
					paa ~ time + totenr + pfrpm + lag1_paa + lag1_pw + lag1_pas + lag1_po,
					pw ~ time + totenr + pfrpm + paa + lag1_pw + lag1_pas + lag1_po,
					pas ~ time + totenr + pfrpm + paa + pw + lag1_pas + lag1_po,
					po ~ time + totenr + pfrpm + paa + pw + pas + lag1_po,
					fyn ~ time + ch + aco + lag1_anayn + lag1_aapyn + lag1_gtyn + 
                                                  lag1_mtias + totenr + pfrpm + paa + pw + pas + po,
					anayn ~ time + ch + aco + fyn + lag1_aapyn + lag1_gtyn + lag1_mtias + 
                                                   totenr + pfrpm + paa + pw + pas + po,
					aapyn ~ time + ch + aco + fyn + anayn + lag1_gtyn + lag1_mtias + 
                                                      totenr + pfrpm + paa + pw + pas + po,
					gtyn ~ time + ch + aco + fyn + anayn + aapyn + lag1_mtias + 
                                                    totenr + pfrpm + paa + pw + pas + po,
					mtias ~ time + ch + aco + fyn + anayn + aapyn + gtyn + lag1_mtias + 
                                                      totenr + pfrpm + paa + pw + pas + po
                                          ))

**Comment by sally741** [comment]
Hello again!
After some more troubleshooting, we think the issue was arising due to a covariate type "truncated normal"--when we changed it, that error message went away. Several of our covariates are proportions (i.e. numbers in the interval [0,1]), so we decided to give them "binary" type instead--that way, predicted values will be guaranteed to lie between 0 and 1. 

Of course, now we have a new error: 
Error in seq. int(min(dim(R))): "from" must be a finite number
which apparently arises from whatever caused the following warning:
min(dim(R)): no non-missing arguments to min; returning Inf.

Does this indicate that the warnings and errors are due to missing values? We are also getting several warnings that missing values are being produced, and I'm not sure if this is a cause for concern.

**Comment by hmSim** [comment]
Hi, Sally.

When using this package, I encountered the same problem. So...did you solve it?

If yes, can you tell me how to solve it?

Best,
Hyunman

**Comment by sally741** [comment]
Hi Hyunman,
The original problem went away when we changed some of the covariate types. In particular, we think there may have been an issue with the "truncated normal" type, so you could try changing to something else (perhaps "normal" or, if your variable is bounded between 0 and 1, you could try "binary"). 
But of course we can't know if the problem is arising for the same reason for you as it was for us. It may even have been a problem specific to our data. 
The error in my final message seems to arise when we assign a variable type as "absorbing" for one of our variables (even though it works for another variable). I suspect a positivity issue, though I'm not sure why that doesn't cause problems if we assign that variable to the "binary" type.
I hope that helps!

**Comment by stmcg** [comment]
Hi Hyunman,

I agree with Sally that the first error message is probably due to the "truncated normal" covariate type. One issue that can cause the first error message is not specifying the elements `point` and `direction` in the `covparams` argument when using the "truncated normal" covariate type (See Appendix C.2 of the Patterns paper for more details). For example, the code Sally posted doesn't specify these elements, which I assume is causing that error message. I'm not sure about the cause of the second error message. 

In any case, feel free to start a new thread or email me (sean_mcgrath@g.harvard.edu) if you have additional questions.

Best,
Sean
