### ISSUE TITLE
Mediational g-formula

### ISSUE THREAD

**Issue by lindsayad** [CausalInference/gfoRmula#21]
I recently read the [2017 article by Lin](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5285457/), and went to the advertised link https://hsph.harvard.edu/causal/software looking for the `mgformula` SAS macro. However, that link now redirects, and the [current software page](https://causalab.sph.harvard.edu/software/) does not contain `mgformula`. I was wondering whether there are any plans to incorporate the mediational work in that article in this repository or elsewhere? (I am most interested in R, which is why I am asking the question here as opposed to on the SAS repository)

**Comment by rwlogan** [comment]
Thanks for your  interest. The SAS version of the mgformula used an older version of the SAS gformula that is no longer supported. Sheng had mentioned, when the R version of the gformula was in development that he might try to create a version of the mgformula based on the R version. You would need to contact him to see if there was any progress in it. As far as I know, there is currently no work being done within our group to implement an R version of the mgformula.

**Comment by lindsayad** [comment]
Great, thank you for the quick response! Do you know if Sheng has a github handle?

**Comment by rwlogan** [comment]
I am sorry, but I don't know. I have not been in contact with him since 2018. I think he moved back to Taiwan.

**Comment by wangchuanhai** [comment]
I apologize for the interruption, but I recently read the article published by Lin in 2017 and visited the provided link https://hsph.harvard.edu/causal/software in search of the SAS macro program, encountering the same issue as you. May I ask if you have managed to contact Sheng? I would be immensely grateful if you could share any information.

**Comment by stmcg** [comment]
I'm sorry -- I don't believe we've managed to contact him in the meantime
