### ISSUE TITLE
Saving the simulated data

### ISSUE THREAD

**Issue by sally741** [CausalInference/gfoRmula#23]
Hello,
Sorry, it's me again! We wanted to save the simulated data, but when we specified sim_data_b=TRUE, the simulated data still didn't seem to be saved. Do we need to specify something else as well? We couldn't find any more information about this in the documentation, but maybe we missed something.
Please let me know!
Thank you,
Sally

**Comment by stmcg** [comment]
Hi Sally,

Hm I haven't come across this before. A few sanity checks that come to mind are: 

1. After setting `sim_data_b = TRUE` in the `gformula` function, are you accessing the element named `sim_data` in the output of the `gformula` function? That is, if `output` is the name of the object returned by the `gformula` function, are you accessing `output$sim_data`?
2. Are you using bootstrapping? If bootstrapping is used, then the simulated data sets are not included in the output.

Best,
Sean

**Comment by sally741** [comment]
We set the number of bootstrap samples to 0 in order to save the simulated datasets. But it's possible we didn't figure out how to refer to the simulated datasets (neither of us is very experienced in R). I'll check what we did there and get back to you. Thank you!

**Comment by sally741** [comment]
Hi Sean,
So, we've named the output gform_sl_1. The command head(gform_sl_1$sim_data) gives output:
[1] NA
And whereas gform_sl_1 is a list of 19 items, if we scroll down in the Global Environment (working in R Studio), the simulated data line looks like this:
$ sim_data : logi NA
Thoughts?
Thank you!

**Comment by stmcg** [comment]
Hi Sally,

Thanks for following up. That is indeed the correct way to access the simulated data sets from the output `gform_sl_1`. 

I'm quite stumped at what the issue may be then... Internally, the package sets the element `sim_data` in the output based on just a few lines of code. So there doesn't seem to be a lot of things internally in the package that can interfere with this. 

A few shots in the dark so-to-speak:
- Did the package give any error messages or warning messages when running the analyses?
- Are you able to access the simulated data sets when running the example applications in the package documentation (modified to set `sim_data_b = TRUE`)
- Heads up about the `_b` when setting `sim_data_b = TRUE` in the `gformula` function
- It may be worth re-running the analyses and saving the result with a different name, say, `gform_sl_2` (and then check `gform_sl_2$sim_data`). If there is a hidden error message, R may not update `gform_sl_1` and so it could be displaying the results before setting `sim_data_b = TRUE` in the `gformula` function

Best,
Sean

**Comment by sally741** [comment]
Thanks Sean, we'll look into that!

**Comment by sally741** [comment]
Hi Sean,
okay, we were able to get it working. I think that was user error on our part! Thanks for clarifying the name of the object for us. 
Best wishes,
Sally
