### ISSUE TITLE
Incorporating survey weights

### ISSUE THREAD

**Issue by JerzyEG** [CausalInference/gfoRmula#28]
Hi,

Is it possible to incorporate survey weights into the fitting of the outcome model for a survival analysis with the gfoRmula package? I believe ‘covparams’ could be used to do so for the models for time-varying covariates, but I’m unaware of an analogous feature for the outcome model. Thanks for the help!  

Best,

Jerzy

**Comment by stmcg** [comment]
Hi Jerzy,

Thanks for checking. That right, it isn't possible to incorporate weights in the outcome model, as the package uses a GLM without weights for the outcome model and doesn't support custom outcome models

Best,
Sean

**Comment by JerzyEG** [comment]
Thanks for the confirmation and for making this package, it's been really helpful in my work!
