### ISSUE TITLE
Custom Parameter Inputs

### ISSUE THREAD

**Issue by rbarnardmayers** [CausalInference/gfoRmula#3]
I know that this package is based on code from the SAS gformula macro. In the original SAS macro there is a way to provide custom input parameters for the effect estimate calculations. Is there a way to do so in the R version as well?

**Comment by stmcg** [comment]
Hi Ruby,

Thanks for posting. I'm responding again here (in addition to your email) in case others come across this question. 

If I'm understanding correctly, you want to directly pass in parameters for the simulation step (skipping the modelling step). This can be done using a covariate of type`"custom"`. The custom fit function can be left blank and the custom predict function can be used to apply your pre-specified coefficients to simulate the covariate at the current time point in the simulation step. It may be helpful to take a quick read through Section C.7 (Specifying a custom covtype) in the [Supplemental Information of the package description](https://www.cell.com/cms/10.1016/j.patter.2020.100008/attachment/4c45f5f4-2f46-439f-bfb2-a7e3e90e9de4/mmc1.pdf).

Below is an example custom fit and predict function for directly passing in parameters for the simulation step, which assumes you have covariates `lag1_A`, `L1`, `L3`, and `t0` in your data set. 
 
```
fit_custom <- function(covparams, covname, obs_data, j){
}

predict_custom <- function(obs_data, newdf, fitcov, time_name, t, condition,
                           covname, ...){
  betas <- c(1,-2,3,-4,5)
  sigma <- 2
  mu <- betas[1] + betas[2] * newdf$lag1_A + betas[3] * newdf$L1 + 
    betas[4] * newdf$L3 + betas[5] * newdf$t0 
  prediction <- rnorm(n = nrow(newdf), mean = mu, sd = sigma)
  return (prediction)
}
```

Best,
Sean
