### ISSUE TITLE
gfoRmula joint intervention error

### ISSUE THREAD

**Issue by chenlan26** [CausalInference/gfoRmula#33]

**Comment by stmcg** [comment]
Hi Alan,

Do you still have this question, or can I mark it as closed? Asking since it looks like you removed the text in the post

Best,
Sean

**Comment by chenlan26** [comment]
Hi Sean,


Thank you for your &nbsp;reply. Yes, you can mark it closed since I’ve solved the problem.&nbsp;


Wish you a nice weekend!


Best,
Alan

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Sean&nbsp;McGrath ***@***.***&gt;;
发送时间：2024年7月7日(星期天) 凌晨0:15
收件人："CausalInference/gfoRmula" ***@***.***&gt;;
抄送："陈兰 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [CausalInference/gfoRmula] gfoRmula joint intervention error (Issue #33)
-----------------------------------

 

 
Hi Alan,
 
Do you still have this question, or can I mark it as closed? Asking since it looks like you removed the text in the post
 
Best,
 Sean
