### ISSUE TITLE
Individual-level treatment effects

### ISSUE THREAD

**Issue by njawadekar** [CausalInference/gfoRmula#37]
Hello,
I am currently trying to use your g-formula (R package) to estimate the controlled direct effect in a competing risks setting (due to death). I am specifically modelling my code off of the vignette provided on pg. 18 of your [R documentation.](https://cran.r-project.org/web/packages/gfoRmula/gfoRmula.pdf)

However, I had a quick question. In addition to the overall average treatment effect (i.e., the difference in g-formula estimates between the 2 specified interventions), I was also interested in retrieving the corresponding individual-level differences in these estimates, prior to the step where the g-formula estimator takes the mean of those differences. Is there an easy way for me to retrieve these individual-level estimates using your package? Thanks in advance!

**Comment by stmcg** [comment]
Hi, I'm not sure if I'm fully understanding. The simulated data sets under each intervention strategy can be accessed if you set the parameter `sim_data_b` to `TRUE` in the `gformula` function (and then access the element `sim_data` in the output). Does this contain what you're looking for?

**Comment by njawadekar** [comment]
Yes, I think that contains what I'm looking for! 

In that case, if I would like to compute the expected individual-level difference in the risk of the outcome between 'Always Treat' and 'Never Treat' (using that gformula vignette provided on pg. 18 of [your documentation](https://cran.r-project.org/web/packages/gfoRmula/gfoRmula.pdf)), then would it be correct for me to simply take the difference in the value of the "poprisk" column for every ID at t0 = 6 (the last timepoint)?

To do this, I have set up my code as follows. If you could verify whether I am thinking through this appropriately, that would be much appreciated!


```
#### Create two simulated dataframes containing "Never Treat" and "Always Treat"
never_treat = as.data.frame(gform_basic$sim_data[2])
always_treat = as.data.frame(gform_basic$sim_data[3])

#### Compute individual-level treatment effects: Get the expected risk at end of follow-up for each ID, and then merge by ID and take the differences of those expected risks
result <- never_treat %>%
  group_by(Never.treat.id) %>%
  summarize(last_never_treat = last(Never.treat.poprisk), .groups = 'drop') %>% # Get the last value of Never.treat.poprisk for each id
  inner_join(
    always_treat %>%
      group_by(Always.treat.id) %>%
      summarize(last_always_treat = last(Always.treat.poprisk), .groups = 'drop'), # Get the last value of Always.treat.poprisk for each id
    by = c("Never.treat.id" = "Always.treat.id")  # Join on the IDs
  ) %>%
  mutate(individual_difference = last_always_treat - last_never_treat) # Take the difference to compute the expected individual-level difference
```

**Comment by stmcg** [comment]
Yes, you should be accessing the never treat and always treat data sets correctly. I'm not familiar with dplyr-style data processing in R, so I can't say for certain whether the code for computing the differences is correct. It looks reasonable though

Regarding whether you are thinking through this appropriately: I can't really comment on the general approach of using the individual-level differences since I'm not familiar with the context of your analysis. A heads up -- the rows in these simulated data sets aren't intended to be (formally) individual treatment effects from my understanding

**Comment by njawadekar** [comment]
Thank you!
