### ISSUE TITLE
Non-parametric modelling within g-formula

### ISSUE THREAD

**Issue by njawadekar** [CausalInference/gfoRmula#38]
I was just wondering if there would be an easy way to allow for non-parametric modelling within this g-formula. For example, let's say I thought I might be able to make better predictions for my outcome, competing event, and covariate models if I were to use non-parametric models (let's say, using the gbart() function using the [BART package](https://cran.r-project.org/web/packages/BART/BART.pdf)). Would there be an easy way for me make this adjustment within gformula() ?

**Comment by stmcg** [comment]
Yes, see Appendix C.7 in the [Patterns paper](https://doi.org/10.1016/j.patter.2020.100008) for custom covariate models and the vignette "Using Custom Outcome Models in gfoRmula" for custom outcome models.

**Comment by njawadekar** [comment]
Thank you!
