### ISSUE TITLE
The example provides an error

### ISSUE THREAD

**Issue by mskypala** [CausalInference/gfoRmula#4]
Hi, 
I'm learning how to use this package and the first example 'Estimating the effect of static treatment strategies on risk of a failure event' provides me with the error 

Error in stri_detect_regex(string, pattern, negate = negate, opts_regex = opts(pattern)) : 
  Syntax error in regexp pattern. (U_REGEX_RULE_SYNTAX)

How can I resolve this?

**Comment by stmcg** [comment]
Hi,

Thanks for posting. Are you running this example by copy and pasting the code from the arXiv pre-print, the Patterns paper, or the package help files? My first thought is that if you copy and paste the code from the arXiv pre-print or the Patterns paper, the symbols for the quotation marks in those papers may not match R's symbol for quotation marks. As a sanity check, I'd first try copy and pasting the code for this example in the help files (accessed by `?gfoRmula::gformula`) and see if you still get this error.

If you are still getting this error, can you provide some more information (eg, the output from running `sessionInfo()` and the code you are running)?

Best,
Sean

**Comment by stmcg** [comment]
I'm closing this issue because I haven't heard back and can't reproduce this error. Please let me know if you are still running into any problems when using the package.
