### ISSUE TITLE
Estimating causal effect of time-fixed treatment

### ISSUE THREAD

**Issue by njawadekar** [CausalInference/gfoRmula#40]
Hello,
I am currently trying to use your package to estimate the controlled direct effect of a **time-fixed** (i.e., defined at baseline only) treatment A on outcome Y, adjusted for time-varying confounders (v_var1, v_var2, v_var3, and v_var4), baseline confounders (bl_var1, bl_var2, vl_var3, bl_var4, bl_var5, vl_var6, bl_var7, bl_var8, & bl_var9), and also accounting for competing risk D.

When I run the gformula function on the above data, I am getting warnings: "glm.fit: fitted probabilities numerically 0 or 1 occurred" , and in addition, the g-form risk in my results between my "Never treat" and "Always treat" are suspiciously almost identical. Therefore, I'm wondering whether I am coding something incorrectly. Would you mind checking the below to see if I am missing something? As you can see, I have defined my treatment model as a function of the baseline covariates.

```
outcome_type <- 'survival'
id <- 'id'
time_points <- 11
time_name <- 't0' 

covnames <- c('A','v_var1', 'v_var2', 'v_var3', 'v_var4')
outcome_name <- 'Y'
compevent_name <- 'D'
covtypes <- c('binary','binary', 'binary', 'binary', 'binary')
histories <- c(lagged, lagavg)
histvars <- list(c('A','v_var1', 'v_var2', 'v_var3','v_var4'), c('A','v_var1', 'v_var2', 'v_var3', 'v_var4'))
covparams <- list(covlink = c('logit','logit','logit','logit','logit'),covmodels = c(
A ~ bl_var1 + bl_var2 + bl_var3 + bl_var4 + bl_var5 + bl_var6 + bl_var7 + bl_var8 +  bl_var9,    
  
v_var1 ~ lag_cumavg1_v_var1 +  lag_cumavg1_v_var2 + lag_cumavg1_v_var3 + lag_cumavg1_v_var4 +
A + bl_var5 + bl_var6 + bl_var7 + bl_var8 +  bl_var9 + as.factor(t0) 

v_var2 ~ v_var1 + lag_cumavg1_v_var1 + lag_cumavg1_v_var2 + lag_cumavg1_v_var3 + lag_cumavg1_v_var4 +
A + bl_var5 + bl_var6 + bl_var7 + bl_var8 +  bl_var9 + as.factor(t0),

v_var3 ~ v_var1 + v_var2 + lag_cumavg1_v_var1 + lag_cumavg1_v_var2 + lag_cumavg1_v_var3 + lag_cumavg1_v_var4 +
A + bl_var5 + bl_var6 + bl_var7 + bl_var8 +  bl_var9 + as.factor(t0),

v_var4 ~ v_var1 + v_var2 + v_var3 + lag_cumavg1_v_var1 + lag_cumavg1_v_var2 + lag_cumavg1_v_var3 + lag_cumavg1_v_var4 +
A + bl_var5 + bl_var6 + bl_var7 + bl_var8 +  bl_var9 + as.factor(t0)))

ymodel <- Y ~ A + v_var1 + v_var2 + v_var3 + v_var4 + bl_var5 + bl_var6 + bl_var7 + bl_var8 +  bl_var9 +  lag1_v_var1 + lag1_v_var2 + lag1_v_var3 + lag1_v_var4 +  as.factor(t0)

compevent_model <- D ~ A + v_var1 + v_var2 + v_var3 + v_var4 + bl_var5 + bl_var6 + bl_var7 + bl_var8 + bl_var9 + lag1_v_var1 + lag1_v_var2 + lag1_v_var3 + lag1_v_var4 + as.factor(t0)

intervention1.A <- list(static, rep(0, time_points))
intervention2.A <- list(static, rep(1, time_points))
int_descript <- c('Never treat', 'Always treat')

nsimul <-  7167  # This is the number of distinct number of subjects in my dataset

gform_cde <- gformula(obs_data = data_long, outcome_type = outcome_type, id = id, time_points = time_points, time_name = time_name, covnames = covnames, outcome_name = outcome_name, 
compevent_name = compevent_name,                       
covtypes = covtypes, covparams = covparams, ymodel = ymodel, 
intervention1.A = intervention1.A,
intervention2.A = intervention2.A,
int_descript = int_descript, histories = histories, histvars = histvars, basecovs = c('bl_var1','bl_var2', 'bl_var3', 'bl_var4', 'bl_var5','bl_var6','bl_var7','bl_var8','bl_var9'), nsimul = nsimul, seed = 1234, sim_data_b = TRUE)
```

**Comment by stmcg** [comment]
I'd try setting `A ~ 1` for the treatment model to start with, as this isn't used in the counterfactual mean estimates under the never treat / always treat strategies. More generally, I'd suggest starting with very simple models (eg, no time-varying confounders) and gradually build up the complexity to see what model is causing the error message. You can also access the fitted models from the output of `gformula` which may help troubleshoot

**Comment by njawadekar** [comment]
Hi, 
I implemented your above suggestions, as I specifically removed the time-varying predictors (i.e., lag_cumavg1_variablename) from my covariate models which predicted v_var1, v_var2, v_var3, and v_var4. After I made this update and re-ran the g-formula, I am no longer getting that warning, ""glm.fit: fitted probabilities numerically 0 or 1 occurred"". 

However, I still need to figure out how to include the time-varying components in my covariate models. Accordingly, I have a couple follow-up questions regarding how I should proceed:

(1) It seems that I was likely getting that 'fitted probabilities' warning because those covariate history variables (i.e., the cumulative average variables) were basically perfectly predicting those covariates at each timepoint. When I looked at the values of the coefficients of those models (particularly the coefficients for the cumavg variables that corresponded to the same covariate that it was predicting), they were quite large.

(2) Related to this, I was wondering whether I should have actually been specifying these covariates (v_var1, v_var2, v_var3, and v_var4) as covtypes 'absorbing' rather than 'binary,' because once their value converts to 1, the value of that covariate will continue to be 1 at that time and all subsequent times. Therefore, as another check, I tried re-running my code while specifying their covtypes as 'absorbing'. However, when I did this, it made the glm.fit fitted probabilities warning come back (regardless of whether I included the cumavg variables in those models)

(3) Given that my covariates v_var1, v_var2, v_var3, and v_var4 are all 'absorbing' variables, yet I am getting the above warning when I make the covtype as 'absorbing' , what other changes do you recommend that I make so that my code will avoid this warning? 

Also FYI - when I specify them as 'absorbing' and when I also add those time-varying cumavg variables back, I am getting the additional warning: "5: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  ... :
  prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases"

**Comment by njawadekar** [comment]
Also, one more observation/question related to my code: after running the above code (which includes a compevent_model that I specified for predicting D), when I look inside the values from the resulting gformula object, I can't figure out why the value of comprisk is FALSE, and furthermore I cannot find my competing event model (predicting D) within any of the coefficient outputs. Do you know why that might be, despite the fact that I specified competing risks in this code?

**Comment by stmcg** [comment]
A few thoughts are below:

- The code in your post doesn't specify the parameter `compevent_model` in the call to the `gformula` function, which may be why you aren't seeing it in the output
- Yes, you should use 'absorbing' covariate types if they will always have the value 1 after initially converting to 1. Otherwise, I can see getting predicted probabilities very close to 1
- My two cents is that these models are likely too richly parameterized for the data set you are working with based on error message you received when using 'absorbing' covariate types

More generally, these threads are meant to discuss specific bugs in the package rather than supporting/troubleshooting analyses using the package. My time is a somewhat limited for this at the moment, but if you want to discuss more you can reach out to my email at sean_mcgrath@g.harvard.edu
