### ISSUE TITLE
Two time points with binary outcome 

### ISSUE THREAD

**Issue by sebastiaan-blank** [CausalInference/gfoRmula#41]
Hello, 

Thank you for the excellent package! 

I have run into a problem in a very specific circumstance. 
I am trying to estimate the  effect of treatment delivered on 2 time points (0,1)  with time varying and baseline variables on a binary outcome. I keep getting "Error in seq.int(min(dim(R))) : 'from' must be a finite number"

I have tried to replicate this with a modified version of the  binary_eofdata set and I get a similar error (at least I presume):

binary_eofdata <- binary_eofdata %>% group_by(id_num) %>% fill(outcome, .direction = c("up")) %>% filter (time < 2)
binary_eofdata <- binary_eofdata %>% mutate(outcome = ifelse(time == 0, NA, outcome))

outcome_type <- 'binary_eof'
id <- 'id_num'
time_name <- 'time'
covnames <- c('cov1', 'cov2', 'treat')
outcome_name <- 'outcome'
histories <- c(lagged, cumavg)
histvars <- list(c('treat', 'cov1', 'cov2'), c('cov1', 'cov2'))
covtypes <- c('binary', 'zero-inflated normal', 'normal')
covparams <- list(covmodels = c(cov1 ~ lag1_treat + lag1_cov1 + lag1_cov2 +
                                  cov3 + time,
                                cov2 ~ lag1_treat + cov1 + lag1_cov1 +
                                  lag1_cov2 + cov3 + time,
                                treat ~ lag1_treat + cumavg_cov1 +
                                  cumavg_cov2 + cov3 + time))
ymodel <- outcome ~  treat + cov1 + cov2 + lag1_cov1 + lag1_cov2 + cov3
intervention1.treat <- list(static, rep(0, 2))
intervention2.treat <- list(threshold, 1, Inf)
int_descript <- c('Never treat', 'Threshold - lower bound 1')
nsimul <- 10000
ncores <- 2

gform_bin_eof <- gformula(obs_data = binary_eofdata, 
                          outcome_type = outcome_type, id = id,
                          time_name = time_name, covnames = covnames,
                          outcome_name = outcome_name, covtypes = covtypes,
                          covparams = covparams, ymodel = ymodel,
                          intervention1.treat = intervention1.treat,
                          intervention2.treat = intervention2.treat,
                          int_descript = int_descript, histories = histories,
                          histvars = histvars, basecovs = c("cov3"),
                          seed = 1234, parallel = TRUE, nsamples = 5,
                          nsimul = nsimul, ncores = ncores)

Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: 'from' must be a finite number 

Thanks, 
Seb

**Comment by stmcg** [comment]
Hi Seb,

Thanks for posting and apologies for the slight delay in getting to this. I believe the issue is stemming from the covariate model fitting, as some of the terms in those models are not identifiable. For example, the terms `time` can't be estimated since only data at time interval 1 are being used to fit those models. It also looks like NA coefficients are also returned for the `lag1_cov2` terms due to multicollinearity in this case (not exactly sure on why this is the case in this example, although I suspect that the main issue in your analysis has to do with including the `time` term). Does this resolve your issue?

Best,
Sean

**Comment by sebastiaan-blank** [comment]
Thanks Sean, 

You are right, it is the time term. Now that it is pointed out it makes complete sense

**Comment by wzb-cell** [comment]
Hello, Sean and Seb

I am also trying to estimate the effect of treatment delivered at 2 time points (0,1) with time-varying and baseline variables on a survival outcome. I keep getting "Error in seq.int(min(dim(R))):  'from' must be a finite number" when undertaking a joint static interventions that sets two time-varying covariates. However, the model with  a static interventions on a binary time-varying covariate  can operate normally. I don't know what's behind the problem.


Code of Joint Interventions:
outcome_type <- 'survival'
id <- 'ID'
time_points <- 2
 time_name <- 't0'
 covnames <- c('L1', 'L2', 'A')
 outcome_name <- 'Y'
 covtypes <- c('binary', 'binary', 'categorical')
 histories <- c(lagged, lagged)
 histvars <- list(c('A', 'L1', 'L2'), c('L1', 'L2'))
 covparams <- list(covmodels = c(L1~lag1_A + lag1_L1 + lag1_L2 +L3+t0,
                                 L2 ~lag1_A + L1 + lag1_L1 +lag1_L2 + L3+t0,
                                 A ~lag1_A + L1 + L2 + lag1_L1 +lag1_L2 + L3+t0))
 ymodel <- Y ~ A + L1 + L2 + L3 + lag1_A + lag1_L1 + lag1_L2 + t0
 intvars = list(c('A', 'L2'), c('A', 'L2'))
 interventions = list(list(c(static, rep(0, 2)),
                           c(static, rep(0, 2))),
                      list(c(static, rep(1, 2)),
                           c(static, rep(1, 2))))
 int_descript <- c('Never treat', 'Always treat')
 nsimul <- 10000
 gform_basic <- gformula(obs_data = long_data,
                           outcome_type = outcome_type, id = id,
                           time_points = time_points, time_name = time_name,
                           covnames = covnames, outcome_name = outcome_name,
                           covtypes = covtypes, covparams = covparams,
                           ymodel = ymodel, intvars = intvars,
                          interventions = interventions,
                           int_descript = int_descript, histories = histories,
                           histvars = histvars, basecovs = c('L3'),
                           nsimul = nsimul, seed = 1234)



Code of the static intervention:
gform_result <- gformula(
  obs_data = long_data,
  id = "ID",
  time_points = 2,
  time_name = "t0",
  covnames = c( "A"), 
  covtypes = c( "categorical"),
  basecovs = c("L1","L2"),
  outcome_name = "Y", 
  outcome_type = "survival", 
  histories = c(lagged),
  histvars = list(c("A")),
  covparams = list(
    covmodels = c(
      A  ~ lag1_A + L1 + L2 + t0)),
  ymodel = Y ~ A + L1 + L2 + lag1_A + t0,
  intvars = list(c("A"), c("A"),c("A")),
  intervention1.A = list(static, rep(3, 2)),
  intervention2.A = list(static, rep(0, 2)),
  intervention3.A = list(static, rep(1, 2)),
  int_descript = c("Never treat", "Always treat","ERW"),
  seed = 123,
  parallel = TRUE,
  nsamples=20,
  nsimul=10000,
  ncores=ncores)

Thanks,
Wzb

**Comment by stmcg** [comment]
Hi, I think this has a similar issue as the one Seb came across. If you have just two time points, the terms of `t0` cannot be estimate in the covariate models since only postbaseline data is used to fit those models. I'd re-run the analysis excluding those terms and see if the error message persists. In general, non-identifiability of terms of the covariate and outcome models are likely creating this error message

**Comment by wzb-cell** [comment]
Thank you very much for your patient explanation, Sean,
As you said, the terms of t0 cannot be estimated in the covariate models. I'd re-run the analysis, excluding terms t0. In addition, I find another problem is that when the analysis includes terms t0, and "covtypes" is "binary", there will be an error message, while when "covtypes" are "categorical", there will be no such error message.
