### ISSUE TITLE
Covariate distributions

### ISSUE THREAD

**Issue by ghost** [CausalInference/gfoRmula#5]
Hi, I'm trying to apply this package(especially, gformula function) to my dataset. Thanks to your effort and this package, I could estimate associations between time-varying exposure and outcome adjusting time-varying feedbacks.

I have two questions.

1. When choosing a truncated normal for a covariate distribution, I obtained an error statement that "Error in truncnorm::rtruncnorm(x = x, mean = mean, sd = est_sd, a = a,  :  unused argument (x = x)". So I searched to know why this error message occurred and found that, in package "truncnorm", rtruncnorm uses argument not x but n (rtruncnorm(n, a=-Inf, b=Inf, mean = 0, sd = 1)). By any chance, is this an error?

2. I need to use poisson and negative binomial distributions for distributions of covariates. So I defined two sets of functions for each covfits_custom and covpredict_custom, respectively, as follows:

Poisson
--------------------------------------------------------------------------------------------------------------------------------------
fit_poisson <- function(covparams, covname, obs_data, j){
  covmodels <- covparams$covmodels
  fit <- stats::glm(formula = as.formula(paste(covmodels[j])), family = "poisson"(link = "log"), data = obs_data, y = TRUE)
  return(fit)
}

predict_poisson <- function(obs_data, newdf, fitcov, time_name, t, condition, covname, ...){
  n <- nrow(newdf)
  theta <- stats::predict(object = fitcov, type = "response", newdata = newdf)
  prediction <- rpois(n = n, lambda = theta)
  return(prediction)
}

--------------------------------------------------------------------------------------------------------------------------------------
Negative binomial
--------------------------------------------------------------------------------------------------------------------------------------
fit_nbinom <- function(covparams, covname, obs_data, j){
  covmodels <- covparams$covmodels
  fit <- MASS::glm.nb(formula = as.formula(paste(covmodels[j])), data = obs_data, y = TRUE)
  return(fit)
}

predict_nbinom <- function(obs_data, newdf, fitcov, time_name, t, condition, covname, ...){
  n <- nrow(newdf)
  theta <- stats::predict(fitcov, type = "response", newdata = newdf)
  prediction <- 
  return(prediction)
}

--------------------------------------------------------------------------------------------------------------------------------------
In both cases, an error statement that In dpois(y, mu, log = TRUE) : non-integer x = 19.718310 are provided. To solve this problem, I have read source codes for this package in this github but I don't know why this error occurred.
Could you help me how to modify or fix the above functions?

Thanks for reading very long writing.

**Comment by stmcg** [comment]
Hi,

Thanks for posting and my apologies for responding to this so late. My responses are below:

1. Yes, the argument should be `n` instead of `x` in the `rtruncnorm` function. Thanks for finding this. I just made a commit fixing this error. 

2. I applied your custom fit and predict functions for the poisson distribution and I'm not getting any error messages. See below for an example, which involves a small modification to the first example in the documentation of the `gformula` function. Seeing the error message you received, perhaps the variable in your data set wasn't a count variable?

```
# Your custom fit and predict functions
fit_poisson <- function(covparams, covname, obs_data, j){
  covmodels <- covparams$covmodels
  fit <- stats::glm(formula = as.formula(paste(covmodels[j])), family = "poisson"(link = "log"), data = obs_data, y = TRUE)
  return(fit)
}
predict_poisson <- function(obs_data, newdf, fitcov, time_name, t, condition, covname, ...){
  n <- nrow(newdf)
  theta <- stats::predict(object = fitcov, type = "response", newdata = newdf)
  prediction <- rpois(n = n, lambda = theta)
  return(prediction)
}

# Making L2 a count variable
basicdata_nocomp$L2 <- round(basicdata_nocomp$L2 - min(basicdata_nocomp$L2))

id <- 'id'
time_points <- 7
time_name <- 't0'
covnames <- c('L1', 'L2', 'A')
outcome_name <- 'Y'
outcome_type <- 'survival'
covtypes <- c('binary', 'custom', 'binary')
histories <- c(lagged, lagavg)
histvars <- list(c('A', 'L1', 'L2'), c('L1', 'L2'))
covparams <- list(covmodels = c(L1 ~ lag1_A + lag_cumavg1_L1 + lag_cumavg1_L2 +
                                  L3 + t0,
                                L2 ~ lag1_A + L1 + lag_cumavg1_L1 +
                                  lag_cumavg1_L2 + L3 + t0,
                                A ~ lag1_A + L1 + L2 + lag_cumavg1_L1 +
                                  lag_cumavg1_L2 + L3 + t0))
ymodel <- Y ~ A + L1 + L2 + L3 + lag1_A + lag1_L1 + lag1_L2 + t0
intvars <- list('A', 'A')
interventions <- list(list(c(static, rep(0, time_points))),
                      list(c(static, rep(1, time_points))))
int_descript <- c('Never treat', 'Always treat')
nsimul <- 10000

gform_basic <- gformula(obs_data = basicdata_nocomp, id = id,
                        time_points = time_points,
                        time_name = time_name, covnames = covnames,
                        outcome_name = outcome_name,
                        outcome_type = outcome_type, covtypes = covtypes,
                        covparams = covparams, ymodel = ymodel,
                        intvars = intvars,
                        interventions = interventions,
                        int_descript = int_descript,
                        histories = histories, histvars = histvars,
                        basecovs = c('L3'), nsimul = nsimul,
                        seed = 1234,
                        covfits_custom = c(NA, fit_poisson, NA),
                        covpredict_custom = c(NA, predict_poisson, NA))
```
