### ISSUE TITLE
Continuous Treatment Example

### ISSUE THREAD

**Issue by calebasaraba** [CausalInference/gfoRmula#7]
Hello -- thank you for this excellent package. I am working on a project with a continuous treatment. In both the manuscript and package documentation you mention that this package can be used for continuous treatments, but I am struggling to implement it. Are there any vignettes or example datasets that show how to use the gformula() function with continuous treatments? Thank you!

**Comment by stmcg** [comment]
Hi, thanks for the question. Example 2 in the paper (https://www.cell.com/patterns/fulltext/S2666-3899(20)30008-8) has a continuous treatment. Heads up that there is a typo in the corresponding description in the paper saying that the treatment is binary (can be seen in the code and data that the treatment is continuous). Apologies for the confusion

**Comment by calebasaraba** [comment]
Thanks so much for your response! I have been able to work through Example 2 and adapting it to the continuous treatment used in my project. I do have two questions that might be very elementary:
- Is it possible to use the package for situations with only baseline covariates, no time-varying covariates? How could one deal with the `cov` arguments in such a use case?
- In the continuous treatment example dataset, has the continuous treatment variable been mean-centered or standardized? I am curious about the interpretation of the threshold value and how to apply it to my situation. It looks like there are no values above 1 in the raw example data, but I think the threshold value refers to setting continuous treatment above 1 throughout -- just want to make sure that is correct.

**Comment by stmcg** [comment]
> * Is it possible to use the package for situations with only baseline covariates, no time-varying covariates? How could one deal with the `cov` arguments in such a use case?

Yes, the package should be able to handle this case. The `covparams`, `covnames`, and `covtypes` arguments should be set to `NULL`. Note that the package hasn't been thoroughly checked for this case since it's a bit overkill for this scenario. 

> * In the continuous treatment example dataset, has the continuous treatment variable been mean-centered or standardized? I am curious about the interpretation of the threshold value and how to apply it to my situation. It looks like there are no values above 1 in the raw example data, but I think the threshold value refers to setting continuous treatment above 1 throughout -- just want to make sure that is correct.

The threshold value corresponds to the raw data rather than after performing mean centering or standardization. You're right that the threshold value of 1 is rather extreme for this example in the sense that this intervention essentially sets everyones' treatment value equal to 1. A threshold of say 0 would have been more instructive
