### ISSUE TITLE
Does make_histories() require data to be sorted? 

### ISSUE THREAD

**Issue by boyercb** [CausalInference/gfoRmula#8]
I was checking over some code for the EPI207 practicum and noticed that the lags created by `make_histories()` function appear to be wrong when the data aren't initially sorted by `id` and `time_name`.  This is caught by the `error_catch()` function when observations are out of order with respect to both `id` and `time_name`; however, it doesn't appear to be caught when data are sorted by `time_name` but  the `id`'s are in random order.

Reproducible Example:

```
d <- basicdata_nocomp

# add random sort variable `u`
d[, u := runif(.N)]

# within correctly sorted `time_name` sort `id`'s randomly
setorderv(d, c('t0', 'u'))


# run g-formula 
id <- 'id'
time_points <- 7
time_name <- 't0'
covnames <- c('L1', 'L2', 'A')
outcome_name <- 'Y'
covtypes <- c('binary', 'normal', 'binary')
histories <- c(lagged)
histvars <- list(c('A', 'L1', 'L2'))
covparams <- list(covmodels = c(L1 ~ lag1_A + lag1_L1 + lag1_L2 +
                                  L3 + t0,
                                L2 ~ lag1_A + L1 + lag1_L1 + lag1_L2
                                + L3 + t0,
                                A ~ lag1_A + L1 + L2 + lag1_L1 +
                                  lag1_L2 + L3 + t0))
ymodel <- Y ~ A + L1 + L2 + L3 + lag1_A + lag1_L1 + lag1_L2 + t0
intvars <- list('A', 'A')
interventions <- list(list(c(static, rep(0, time_points))),
                      list(c(static, rep(1, time_points))))
int_descript <- c('Never treat', 'Always treat')
nsimul <- 10000

gform_basic_nocomp <- gformula_survival(obs_data = d, id = id,
                                        time_points = time_points,
                                        time_name = time_name, covnames = covnames,
                                        outcome_name = outcome_name,
                                        covtypes = covtypes,
                                        covparams = covparams, ymodel = ymodel,
                                        intvars = intvars,
                                        interventions = interventions,
                                        int_descript = int_descript,
                                        histories = histories, histvars = histvars,
                                        basecovs = c('L3'), nsimul = nsimul,
                                        model_fits = TRUE,
                                        seed = 1234)

```

When I run the code above, no issue is caught by `error_catch()` but if you now dig into the model fit object the lags are clearly wrong:

```
> head(gform_basic_nocomp$fits$L1$data)
   id t0 L1         L2 L3 A Y         u lag1_A lag1_L1    lag1_L2
1:  1  1  0 -0.9254032  5 1 0 0.2099770      1       0  1.0593103
2:  1  2  0 -0.9899824  5 0 0 0.6037477      1       1 -1.0870209
3:  1  3  1  1.0057421  5 1 0 0.9028938      1       0 -0.8787897
4:  1  4  1 -1.1956468  5 1 0 0.2185181      1       1  1.0016411
5:  1  5  0 -0.9697723  5 1 0 0.1589061      1       0 -0.8973752
6:  1  6  1 -1.0887002  5 1 0 0.3048004      0       1  1.1533093
   newid
1:     1
2:     1
3:     1
4:     1
5:     1
6:     1
```

**Comment by stmcg** [comment]
Thanks for posting. Yes, the make history functions indeed assume that the data are sorted by ``id`` and ``time_name``. Our intention is that users supply a data set sorted in this way for the ``gformula`` function. Since these functions are just intended to be used inside the ``gformula`` function, my inclination is to expand the error checking to flag these instances. Does this make sense?

**Comment by boyercb** [comment]
Yeah I think that totally makes sense for `make_histories()`, although I think some of the other functions like `cumavg()` aren't just internal but are exported to the namespace? I haven't dug into it to check but wouldn't this affect their use outside of `gfoRmula` functions?

**Comment by stmcg** [comment]
Oh I see, yes that's true that the make history functions are exported to the namespace (as they ultimately need to get passed into the `gformula` function by the user). I meant to say that those functions were written just for being applied in the `gformula` function, regardless of whether they are passed in to the `gformula` function by the user or called internally. That is, we weren't intending for those functions to be used for general data wrangling for longitudinal dat sets, which would require the code to be written in more generality

**Comment by stmcg** [comment]
Commit 26f9e66 includes a check that the data set is sorted by `id` and `time_name`
